knowledge_representation: LTMCMap< LTMCImpl > Class Template Reference
LTMCMap< LTMCImpl > Class Template Reference
An instance of the Map concept, which represents a single 2D frame of reference.
#include <LTMCMap.h>
Public Member Functions
LTMCMap (uint entity_id, uint map_id, std::string name, LongTermMemoryConduitInterface< LTMCImpl > &ltmc)
Build a map from its identifying components.
bool rename (const std::string &new_name)
Renames a map.
uint getId ()
Get's the map's id (not its entity ID)
PointImpl addPoint (const std::string &name, double x, double y)
Add a new point to the map.
PoseImpl addPose (const std::string &name, double x, double y, double theta)
Add a new pose to the map.
PoseImpl addPose (const std::string &name, double x1, double y1, double x2, double y2)
Add a new pose using two points.
RegionImpl addRegion (const std::string &name, const std::vector< std::pair< double, double > > &points)
Add a new region to the map.
DoorImpl addDoor (const std::string &name, double x_0, double y_0, double x_1, double y_1)
Add a new door to the map.
boost::optional< PointImpl > getPoint (const std::string &name)
Retrieve an existing point by its unique name.
boost::optional< PoseImpl > getPose (const std::string &name)
Retrieve an existing pose by its unique name.
boost::optional< RegionImpl > getRegion (const std::string &name)
Retrieve an existing region by its unique name.
boost::optional< DoorImpl > getDoor (const std::string &name)
Retrieve an existing door by its unique name.
std::vector< PointImpl > getAllPoints ()
Get all points that belong to this map.
std::vector< PoseImpl > getAllPoses ()
Get all poses that belong to this map.
std::vector< RegionImpl > getAllRegions ()
Get all regions that belong to this map.
std::vector< DoorImpl > getAllDoors ()
Get all doors that belong to this map.
LTMCMap deepCopy (const std::string &with_name)
Creates a copy of all of the map's owned geometry.
Public Member Functions inherited from LTMCInstance< LTMCImpl >
LTMCInstance (uint entity_id, std::string name, LongTermMemoryConduitInterface< LTMCImpl > &ltmc)
Build an instance with a given name.
boost::optional< std::string > getName ()
Convenience for getting name attribute.
bool makeInstanceOf (const LTMCConcept< LTMCImpl > &concept)
Attempts to make this instance also an instance of the given concept.
std::vector< LTMCConcept< LTMCImpl > > getConcepts () const
Get all concepts that this instance is transitively an instance of.
std::vector< LTMCConcept< LTMCImpl > > getConceptsRecursive () const
Get all concepts that this instance is transitively an instance of.
bool hasConcept (const LTMCConcept< LTMCImpl > &concept) const
whether instance descends from the concept recursively
bool hasConceptRecursively (const LTMCConcept< LTMCImpl > &concept) const
whether instance descends from the concept recursively
Public Member Functions inherited from LTMCEntity< LTMCImpl >
bool addAttribute (const std::string &attribute_name, EntityId other_entity_id)
Set an attribute which points to some other valid entity.
bool addAttribute (const std::string &attribute_name, const LTMCEntity &other_entity)
Set an attribute which points to some other valid entity.
bool addAttribute (const std::string &attribute_name, bool bool_val)
Set a bool-valued attribute on this entity.
bool addAttribute (const std::string &attribute_name, int int_val)
Set a int-valued attribute on this entity.
bool addAttribute (const std::string &attribute_name, double float_val)
Set a float-valued attribute on this entity.
bool addAttribute (const std::string &attribute_name, const std::string &string_val)
Set a string-valued attribute on this entity.
bool addAttribute (const std::string &attribute_name, const char *string_val)
Set a string-valued attribute on this entity.
int removeAttribute (const std::string &attribute_name)
Unsets all values of a given attribute on this entity.
std::vector< EntityAttribute > getAttributes () const
Get the name and value of all attributes set for this entity.
std::vector< EntityAttribute > getAttributes (const std::string &attribute_name) const
Get all values for an attribute of a given name.
boost::optional< std::string > getName ()
Get the name of an entity, if it has one Not all entities have names, but some specific types of entities (e.g. LTMCConcept, LTMCMap, and other geometry types) must have names). These subclasses will override this method to return a non-optional string.
bool deleteEntity ()
Deletes an entity and any other entities and relations that rely on it.
bool isValid () const
Verifies that the entity still exists in the LTMC An entity can be invalidated if it is explicitly deleted from the LTMC, or if it is removed as a result of other helpers that delete entities.
Detailed Description
template<typename LTMCImpl>
class knowledge_rep::LTMCMap< LTMCImpl >
An instance of the Map concept, which represents a single 2D frame of reference.
Unlike instances of other concepts, maps must be uniquely named
Template Parameters
LTMCImpl
Definition at line 19 of file LTMCMap.h.
Constructor & Destructor Documentation
LTMCMap()
LTMCMap (uint entity_id, uint map_id, std::string name, LongTermMemoryConduitInterface< LTMCImpl > & ltmc) inline
Build a map from its identifying components.
Map IDs aren't exposed, so this constructor shouldn't be called outside of the library. Create and retrieve maps using other methods on LTMC.
Parameters
entity_id
map_id
name
ltmc
Definition at line 42 of file LTMCMap.h.
Member Function Documentation
rename()
bool rename (const std::string & new_name) inline
Renames a map.
Due to special uniqueness constraints on map names, you need to use this method instead of manually adjusting the name attribute.
Parameters
new_name
Returns
true if the rename succeeded
Definition at line 55 of file LTMCMap.h.
getId()
uint getId () inline
Get's the map's id (not its entity ID)
Map's are indexed by their own space of IDs. This prevents edge cases where a plain entity ID could be coerced to be an instance of a map, without respecting unique constraints for maps.
Returns
Definition at line 77 of file LTMCMap.h.
addPose() [1/2]
PoseImpl addPose (const std::string & name, double x, double y, double theta) inline
Add a new pose to the map.
The pose is assumed to be in the map frame
Parameters
name name of the pose to add
x X coordinate of the pose position
y Y coordinate of the pose position
theta orientation of the pose
Definition at line 100 of file LTMCMap.h.
Referenced by LTMCMap< LTMCImpl >::addPose(), and LTMCMap< LTMCImpl >::deepCopy().
addPose() [2/2]
PoseImpl addPose (const std::string & name, double x1, double y1, double x2, double y2) inline
Add a new pose using two points.
Coordinates are taken to be in the map frame. This convenience method is simply intended to prevent atan2 usage bugs in client code.
Parameters
name name of the pose to add
x1 X coordinate of the pose position
y1 Y coordinate of the pose position
x2 X coordinate of a second point along the direction of the pose orientation
y2 Y coordinate of a second point along the direction of the pose orientation
Definition at line 117 of file LTMCMap.h.
References LTMCMap< LTMCImpl >::addPose().
deepCopy()
LTMCMap deepCopy (const std::string & with_name) inline
Creates a copy of all of the map's owned geometry.
Parameters
with_name the name to use for the new map
Returns
the copied map
Definition at line 207 of file LTMCMap.h.
References LTMCMap< LTMCImpl >::addDoor(), LTMCMap< LTMCImpl >::addPoint(), LTMCMap< LTMCImpl >::addPose(), LTMCMap< LTMCImpl >::addRegion(), LTMCMap< LTMCImpl >::getAllDoors(), LTMCMap< LTMCImpl >::getAllPoints(), LTMCMap< LTMCImpl >::getAllPoses(), and LTMCMap< LTMCImpl >::getAllRegions().
The documentation for this class was generated from the following files:
include/knowledge_representation/LongTermMemoryConduitInterface.h
include/knowledge_representation/LTMCMap.h