knowledge_representation: LTMCConcept< LTMCImpl > Class Template Reference
LTMCConcept< LTMCImpl > Class Template Reference
A LTMCEntity representing a Concept; the abstract idea of something.
#include <LTMCConcept.h>
Public Member Functions
Gets the name of the concept
All concepts must have a name, as we don't expect to deal with ideas that don't at least have a name to ground them
Returns
std::string getName () const
Get entities that directly instantiate this concept.
std::vector< InstanceImpl > getInstances () const
Get entities that directly instantiate this concept.
int removeInstances () const
Remove all entities that are directly an instance of this concept.
int removeInstancesRecursive () const
Recursively remove instances of the concept.
InstanceImpl createInstance () const
Create a fresh instance of this concept.
boost::optional< InstanceImpl > createInstance (const std::string &name) const
Create an instance of the concept and give it a particular name.
std::vector< LTMCConcept > getChildren () const
Get all concepts that are direct children of this concept.
std::vector< LTMCConcept > getChildrenRecursive () const
Get all concepts that are descended from this concept.
bool removeReferences ()
Removes all references to a concept.
bool operator== (const LTMCConcept &other) const
Get entities that directly instantiate this concept.
bool operator!= (const LTMCConcept &other) const
Get entities that directly instantiate this concept.
bool isValid ()
Get entities that directly instantiate this concept.
Detailed Description
template<typename LTMCImpl>
class knowledge_rep::LTMCConcept< LTMCImpl >
A LTMCEntity representing a Concept; the abstract idea of something.
Definition at line 19 of file LongTermMemoryConduitInterface.h.
Member Function Documentation
getName()
std::string getName () const inline
Get entities that directly instantiate this concept.
Returns
a list of all entities that are instances of this concept
Definition at line 32 of file LTMCConcept.h.
getInstances()
std::vector<InstanceImpl> getInstances () const inline
Get entities that directly instantiate this concept.
Returns
a list of all entities that are instances of this concept
Definition at line 40 of file LTMCConcept.h.
removeInstances()
int removeInstances () const inline
Remove all entities that are directly an instance of this concept.
Returns
the number of instances removed
Definition at line 50 of file LTMCConcept.h.
removeInstancesRecursive()
int removeInstancesRecursive () const inline
Recursively remove instances of the concept.
An instance of a given concept "C" is transitively an instance of any concept that that defines an "is_a" relation with "C". For example, if the concept of apple "is_a" concept of fruit, then removing instances of fruit will remove all instances of apple.
Returns
the number of instances removed
Definition at line 63 of file LTMCConcept.h.
createInstance() [1/2]
InstanceImpl createInstance () const inline
Create a fresh instance of this concept.
Returns
a new entity that is an instance of this concept
Definition at line 72 of file LTMCConcept.h.
References LTMCInstance< LTMCImpl >::makeInstanceOf().
Referenced by LTMCConcept< LTMCImpl >::createInstance().
createInstance() [2/2]
boost::optional<InstanceImpl> createInstance (const std::string & name) const inline
Create an instance of the concept and give it a particular name.
Parameters
name the name to give the instance
Returns
the created instance, or empty if the instance cannot be created (as when the name is taken)
Definition at line 85 of file LTMCConcept.h.
References LTMCConcept< LTMCImpl >::createInstance().
getChildren()
std::vector<LTMCConcept> getChildren () const inline
Get all concepts that are direct children of this concept.
A child is a concept that has an is_a attribute pointing at this concept.
Returns
all direct childern
Definition at line 103 of file LTMCConcept.h.
getChildrenRecursive()
std::vector<LTMCConcept> getChildrenRecursive () const inline
Get all concepts that are descended from this concept.
A child is a concept that has an is_a attribute pointing at this concept.
Returns
Definition at line 114 of file LTMCConcept.h.
removeReferences()
bool removeReferences () inline
Removes all references to a concept.
References include all entity-attributes that refer to this concept. But note that this method doesn't delete the entities that are the subjects of the references. This means that all instances of this concept will continue to exist, but they will no longer be identified as instances of this concept.
Parameters
concept_name
Returns
Definition at line 128 of file LTMCConcept.h.
operator==()
bool operator== (const LTMCConcept< LTMCImpl > & other) const inline
Get entities that directly instantiate this concept.
Returns
a list of all entities that are instances of this concept
Definition at line 146 of file LTMCConcept.h.
operator!=()
bool operator!= (const LTMCConcept< LTMCImpl > & other) const inline
Get entities that directly instantiate this concept.
Returns
a list of all entities that are instances of this concept
Definition at line 151 of file LTMCConcept.h.
isValid()
bool isValid () inline
Get entities that directly instantiate this concept.
Returns
a list of all entities that are instances of this concept
Definition at line 156 of file LTMCConcept.h.
The documentation for this class was generated from the following files:
include/knowledge_representation/LongTermMemoryConduitInterface.h
include/knowledge_representation/LTMCConcept.h