knowledge_representation: LTMCInstance< LTMCImpl > Class Template Reference
LTMCInstance< LTMCImpl > Class Template Reference
Represents an Entity that is an Instance of some Concept.
#include <LTMCInstance.h>
Public Member Functions
LTMCInstance (uint entity_id, std::string name, LongTermMemoryConduitInterface< LTMCImpl > &ltmc)
Build an instance with a given name.
boost::optional< std::string > getName ()
Convenience for getting name attribute.
bool makeInstanceOf (const LTMCConcept< LTMCImpl > &concept)
Attempts to make this instance also an instance of the given concept.
std::vector< LTMCConcept< LTMCImpl > > getConcepts () const
Get all concepts that this instance is transitively an instance of.
std::vector< LTMCConcept< LTMCImpl > > getConceptsRecursive () const
Get all concepts that this instance is transitively an instance of.
bool hasConcept (const LTMCConcept< LTMCImpl > &concept) const
whether instance descends from the concept recursively
bool hasConceptRecursively (const LTMCConcept< LTMCImpl > &concept) const
whether instance descends from the concept recursively
Detailed Description
template<typename LTMCImpl>
class knowledge_rep::LTMCInstance< LTMCImpl >
Represents an Entity that is an Instance of some Concept.
Instances are like regular entities, but they have at least one Concept which they are directly an instance of.
Definition at line 22 of file LongTermMemoryConduitInterface.h.
Constructor & Destructor Documentation
LTMCInstance()
LTMCInstance (uint entity_id, std::string name, LongTermMemoryConduitInterface< LTMCImpl > & ltmc) inline
Build an instance with a given name.
Note that no validation is performed on construction; the name and entity id are presumed to exist, and the behavior is undefined if they do not.
Parameters
entity_id
name
ltmc
Definition at line 31 of file LTMCInstance.h.
Member Function Documentation
getName()
boost::optional<std::string> getName () inline
Convenience for getting name attribute.
Caching is provided for name since it's so commonly used. Note that behavior is undefined if more than one name attribute is set on the instance.
Returns
name, if it is set
Definition at line 47 of file LTMCInstance.h.
makeInstanceOf()
bool makeInstanceOf (const LTMCConcept< LTMCImpl > & concept) inline
Attempts to make this instance also an instance of the given concept.
Fails if this instance is already an instance of the concept.
Parameters
concept The concept to make this entity an instance of
Returns
whether this instance was newly made an instance of the given concept
Definition at line 70 of file LTMCInstance.h.
Referenced by LTMCConcept< LTMCImpl >::createInstance().
getConcepts()
std::vector<LTMCConcept<LTMCImpl> > getConcepts () const inline
Get all concepts that this instance is transitively an instance of.
For example, if an entity A "instance_of" concept named apple, and apple "is_a" concept of fruit, then getConcepts will return the concepts of both apple and fruit.
Returns
Definition at line 82 of file LTMCInstance.h.
Referenced by LTMCInstance< LTMCImpl >::hasConcept().
getConceptsRecursive()
std::vector<LTMCConcept<LTMCImpl> > getConceptsRecursive () const inline
Get all concepts that this instance is transitively an instance of.
For example, if an entity A "instance_of" concept named apple, and apple "is_a" concept of fruit, then getConcepts will return the concepts of both apple and fruit.
Returns
Definition at line 94 of file LTMCInstance.h.
Referenced by LTMCInstance< LTMCImpl >::hasConceptRecursively().
hasConcept()
bool hasConcept (const LTMCConcept< LTMCImpl > & concept) const inline
whether instance descends from the concept recursively
Returns
Definition at line 102 of file LTMCInstance.h.
References LTMCInstance< LTMCImpl >::getConcepts().
hasConceptRecursively()
bool hasConceptRecursively (const LTMCConcept< LTMCImpl > & concept) const inline
whether instance descends from the concept recursively
Returns
Definition at line 111 of file LTMCInstance.h.
References LTMCInstance< LTMCImpl >::getConceptsRecursive().
The documentation for this class was generated from the following files:
include/knowledge_representation/LongTermMemoryConduitInterface.h
include/knowledge_representation/LTMCInstance.h