knowledge_representation: LongTermMemoryConduitInterface< Impl > Class Template Reference
LongTermMemoryConduitInterface< Impl > Class Template Reference
Interface that defines the primary means of interacting with the knowledge base.
#include <LongTermMemoryConduitInterface.h>
Public Member Functions
bool entityExists (uint id) const
Check whether an entity ID is currently tracked in the database.
EntityImpl addEntity ()
Inserts a new entity into the database.
bool addEntity (uint id)
Attempts to create an entity with a specific ID.
boost::optional< EntityImpl > getEntity (uint entity_id)
Returns an entity with the given ID, if it exists.
boost::optional< InstanceImpl > getInstance (uint entity_id)
Returns an instance with the given ID, if it exists.
boost::optional< ConceptImpl > getConcept (uint entity_id)
Returns an concept with the given ID, if it exists.
boost::optional< MapImpl > getMap (uint entity_id)
Returns a map with the given ID, if it exists.
boost::optional< PointImpl > getPoint (uint entity_id)
Returns a point with the given ID, if it exists.
boost::optional< PoseImpl > getPose (uint entity_id)
Returns a pose with the given ID, if it exists.
boost::optional< RegionImpl > getRegion (uint entity_id)
Returns a region with the given ID, if it exists.
boost::optional< DoorImpl > getDoor (uint entity_id)
Returns a door with the given ID, if it exists.
bool deleteAttribute (const std::string &name)
Remove an attribute from the schema.
bool attributeExists (const std::string &name) const
Check whether an attribute exists in the current schema.
std::vector< EntityImpl > getAllEntities ()
Get all current valid entities.
std::vector< ConceptImpl > getAllConcepts ()
Queries for all entities that are marked as concepts.
std::vector< InstanceImpl > getAllInstances ()
Queries for all entities that are identified as instances.
std::vector< MapImpl > getAllMaps ()
Queries for all entities that are identified as maps.
std::vector< std::pair< std::string, int > > getAllAttributes () const
Retrieves all attributes.
std::vector< EntityAttribute > getAllEntityAttributes ()
Retrieves all entity attributes.
uint deleteAllEntities ()
Remove all entities and all entity attributes except for the robot.
uint deleteAllAttributes ()
Remove all attributes except those defined in the schema as defaults.
ConceptImpl getConcept (const std::string &name)
Retrieves a concept of the given name, or creates one with the name if no such concept exists.
MapImpl getMap (const std::string &name)
Retrieves a map of the given name, or creates one with the name if no such map exists.
InstanceImpl getRobot ()
Gets the instance representing the robot.
bool makeConcept (uint id, std::string name)
A convenience for turning an existing entity ID into a concept.
Detailed Description
template<typename Impl>
class knowledge_rep::LongTermMemoryConduitInterface< Impl >
Interface that defines the primary means of interacting with the knowledge base.
This class implements the Curiously Recurring Template Pattern (CRTP) to enable multiple database backend implementations while maintaining a static interface with no runtime dispatch. You can read more about this pattern here: https://www.fluentcpp.com/2017/05/12/curiously-recurring-template-pattern/
As a result, the implementation of the knowledgebase is completely defined in subclasses of this interface, one for each backend implementation. These are expected to behave essentially identically, so documentation is presented here.
Definition at line 59 of file LongTermMemoryConduitInterface.h.
Member Function Documentation
entityExists()
bool entityExists (uint id) const inline
Check whether an entity ID is currently tracked in the database.
Parameters
id the ID to check for
Returns
whether there is an entity with the given ID
Definition at line 135 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::entityExists().
Referenced by LongTermMemoryConduitInterface< Impl >::entityExists().
addEntity() [1/2]
EntityImpl addEntity () inline
Inserts a new entity into the database.
Returns
the new entity
Definition at line 144 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::addEntity().
Referenced by LongTermMemoryConduitInterface< Impl >::addEntity(), and LTMCConcept< LTMCImpl >::createInstance().
addEntity() [2/2]
bool addEntity (uint id) inline
Attempts to create an entity with a specific ID.
Parameters
id
Returns
whether an entity with the given ID was created
Definition at line 154 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::addEntity().
getEntity()
boost::optional< EntityImpl > getEntity (uint entity_id) inline
Returns an entity with the given ID, if it exists.
Parameters
entity_id the ID of the entity to fetch
Returns
the entity requested, or an empty optional if no such entity exists
Definition at line 164 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getEntity().
Referenced by LongTermMemoryConduitInterface< Impl >::getEntity(), and LTMCConcept< LTMCImpl >::removeReferences().
getInstance()
boost::optional< InstanceImpl > getInstance (uint entity_id) inline
Returns an instance with the given ID, if it exists.
Parameters
entity_id the ID of the instance to fetch
Returns
the instance requested, or an empty optional if no such instance exists
Definition at line 174 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getInstance().
Referenced by LongTermMemoryConduitInterface< Impl >::getInstance().
getConcept() [1/2]
boost::optional< ConceptImpl > getConcept (uint entity_id) inline
Returns an concept with the given ID, if it exists.
Parameters
entity_id the ID of the concept to fetch
Returns
the concept requested, or an empty optional if no such concept exists
Definition at line 184 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getConcept().
Referenced by LongTermMemoryConduitInterface< Impl >::getConcept(), and LTMCConcept< LTMCImpl >::isValid().
getMap() [1/2]
boost::optional< MapImpl > getMap (uint entity_id) inline
Returns a map with the given ID, if it exists.
Parameters
entity_id the ID of the map to fetch
Returns
the map requested, or an empty optional if no such map exists
Definition at line 194 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getMap().
Referenced by LongTermMemoryConduitInterface< Impl >::getMap().
getPoint()
boost::optional< PointImpl > getPoint (uint entity_id) inline
Returns a point with the given ID, if it exists.
Parameters
entity_id the ID of the point to fetch
Returns
the point requested, or an empty optional if no such point exists
Definition at line 204 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getPoint().
Referenced by LongTermMemoryConduitInterface< Impl >::getPoint().
getPose()
boost::optional< PoseImpl > getPose (uint entity_id) inline
Returns a pose with the given ID, if it exists.
Parameters
entity_id the ID of the pose to fetch
Returns
the pose requested, or an empty optional if no such pose exists
Definition at line 214 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getPose().
Referenced by LongTermMemoryConduitInterface< Impl >::getPose().
getRegion()
boost::optional< RegionImpl > getRegion (uint entity_id) inline
Returns a region with the given ID, if it exists.
Useful for discovering whether an ID is a region
Parameters
entity_id the ID of the region to fetch
Returns
the region requested, or an empty optional if no such region exists
Definition at line 226 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getRegion().
Referenced by LongTermMemoryConduitInterface< Impl >::getRegion().
getDoor()
boost::optional< DoorImpl > getDoor (uint entity_id) inline
Returns a door with the given ID, if it exists.
Useful for discovering whether an ID is a door
Parameters
entity_id the ID of the door to fetch
Returns
the door requested, or an empty optional if no such door exists
Definition at line 238 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getDoor().
Referenced by LongTermMemoryConduitInterface< Impl >::getDoor().
deleteAttribute()
bool deleteAttribute (const std::string & name) inline
Remove an attribute from the schema.
This will also remove all uses of this attribute.
Parameters
name
Returns
whether the attribute was removed
Definition at line 252 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::deleteAttribute().
Referenced by LongTermMemoryConduitInterface< Impl >::deleteAttribute().
attributeExists()
bool attributeExists (const std::string & name) const inline
Check whether an attribute exists in the current schema.
Parameters
name
Returns
Definition at line 263 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::attributeExists().
Referenced by LongTermMemoryConduitInterface< Impl >::attributeExists().
getAllEntities()
std::vector< EntityImpl > getAllEntities () inline
Get all current valid entities.
Returns
list of all entities
Definition at line 274 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getAllEntities().
Referenced by LongTermMemoryConduitInterface< Impl >::getAllEntities().
getAllConcepts()
std::vector< ConceptImpl > getAllConcepts () inline
Queries for all entities that are marked as concepts.
Returns
list of all concepts in the LTMC
Definition at line 283 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getAllConcepts().
Referenced by LongTermMemoryConduitInterface< Impl >::getAllConcepts().
getAllInstances()
std::vector< InstanceImpl > getAllInstances () inline
Queries for all entities that are identified as instances.
Returns
all instances in the LTMC
Definition at line 292 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getAllInstances().
Referenced by LongTermMemoryConduitInterface< Impl >::getAllInstances().
getAllMaps()
std::vector< MapImpl > getAllMaps () inline
Queries for all entities that are identified as maps.
No operations are provided for bulk retrieving geometry as they can easily be accomplished on a map by map basis.
Returns
all maps in the LTMC
Definition at line 304 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getAllMaps().
Referenced by LongTermMemoryConduitInterface< Impl >::getAllMaps().
getAllAttributes()
std::vector< std::pair< std::string, int > > getAllAttributes () const inline
Retrieves all attributes.
Returns
a list of tuples. First element of each is the attribute name, the second is the allowed type for the attribute
Definition at line 314 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getAllAttributes().
Referenced by LongTermMemoryConduitInterface< Impl >::getAllAttributes().
getAllEntityAttributes()
std::vector< EntityAttribute > getAllEntityAttributes () inline
Retrieves all entity attributes.
Returns
a list of entity attributes
Definition at line 323 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getAllEntityAttributes().
Referenced by LongTermMemoryConduitInterface< Impl >::getAllEntityAttributes().
deleteAllEntities()
uint deleteAllEntities () inline
Remove all entities and all entity attributes except for the robot.
Returns
The number of entities removed
Definition at line 332 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::deleteAllEntities().
Referenced by LongTermMemoryConduitInterface< Impl >::deleteAllEntities().
deleteAllAttributes()
uint deleteAllAttributes () inline
Remove all attributes except those defined in the schema as defaults.
Returns
The number of attributes removed
Definition at line 341 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::deleteAllAttributes().
Referenced by LongTermMemoryConduitInterface< Impl >::deleteAllAttributes().
getConcept() [2/2]
ConceptImpl getConcept (const std::string & name) inline
Retrieves a concept of the given name, or creates one with the name if no such concept exists.
Parameters
name
Returns
the existing concept, or the newly created one. In either case, the concept will at least have the name passed as a parameter.
Definition at line 379 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getConcept().
getMap() [2/2]
MapImpl getMap (const std::string & name) inline
Retrieves a map of the given name, or creates one with the name if no such map exists.
Parameters
name
Returns
Definition at line 389 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getMap().
getRobot()
InstanceImpl getRobot () inline
Gets the instance representing the robot.
Returns
an instance representing the robot the LTMC is running on
Definition at line 398 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::getRobot().
Referenced by LongTermMemoryConduitInterface< Impl >::getRobot().
makeConcept()
bool makeConcept (uint id, std::string name) inline
A convenience for turning an existing entity ID into a concept.
Parameters
id The ID of an existing entity
name The desired name of the concept
Returns
whether the entity with the given ID was turned into a concept with the given name
Definition at line 410 of file LongTermMemoryConduitInterface.h.
References LongTermMemoryConduitInterface< Impl >::makeConcept().
Referenced by LongTermMemoryConduitInterface< Impl >::makeConcept(), and LTMCConcept< LTMCImpl >::removeReferences().
The documentation for this class was generated from the following file:
include/knowledge_representation/LongTermMemoryConduitInterface.h