#!/usr/bin/env python
# Copyright (C) 2016 Toyota Motor Corporation

from traitlets.config.loader import Config
try:
    get_ipython
except NameError:
    nested = 0
    cfg = Config()
else:
    cfg = Config()
    nested = 1



from IPython.terminal.embed import InteractiveShellEmbed
shell = InteractiveShellEmbed(config=cfg,
                              banner1="knowledge_representation Interactive Shell 0.1.0",
                              exit_msg="Leaving knowledge_representation Interactive Shell")

LOGO = r"""
           __             ___  __   __   ___      __   ___  __     
|__/ |\ | /  \ |  | |    |__  |  \ / _` |__      |__) |__  |__)    
|  \ | \| \__/ |/\| |___ |___ |__/ \__> |___ ___ |  \ |___ |                                                       
"""

import knowledge_representation

ltmc = knowledge_representation.get_default_ltmc()

shell(LOGO)