#!/usr/bin/env python
import knowledge_representation
from knowledge_representation.map_loader import load_map_from_yaml, populate_with_map_annotations
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("map_yaml_path", type=str)
    args = parser.parse_args()
    ltmc = knowledge_representation.get_default_ltmc()
    map_name, annotations = load_map_from_yaml(args.map_yaml_path)
    populate_with_map_annotations(ltmc, map_name, *annotations)


if __name__ == "__main__":
    main()
