#!/usr/bin/env python
import knowledge_representation
from knowledge_representation import Entity, Concept, Instance, Map, Point, Pose, Region
from tabulate import tabulate
import argparse

ltmc = knowledge_representation.get_default_ltmc()


def summarize_ltmc():
    all_entities = ltmc.get_all_entities()
    rows = []
    for entity in all_entities:
        typed = id_to_typed_wrapper(entity.entity_id)
        rows.append([entity.entity_id, str(typed)])

    print(tabulate(rows, ["Entity", "Summary"]))


def id_to_typed_wrapper(entity_id):
    as_entity = Entity(entity_id, ltmc)
    if not as_entity.is_valid():
        return None
    as_concept = ltmc.get_concept(entity_id)
    if as_concept:
        return as_concept
    as_instance = ltmc.get_instance(entity_id)
    if not as_instance:
        return as_entity
    concepts = set(map(lambda x: x.get_name(), as_instance.get_concepts()))
    if "map" in concepts:
        return ltmc.get_map(entity_id)
    if "point" in concepts:
        return ltmc.get_point(entity_id)
    if "pose" in concepts:
        return ltmc.get_pose(entity_id)
    if "region" in concepts:
        return ltmc.get_region(entity_id)

    return as_instance


def about_id(entity_id, show_attributes=True):
    typed = id_to_typed_wrapper(entity_id)
    if isinstance(typed, Concept):
        about_concept(typed.name)
    elif isinstance(typed, Instance):
        as_instance = ltmc.get_instance(entity_id)
        print("Instance of: {}".format(map(lambda x: x.get_name(), as_instance.get_concepts())))

    if isinstance(typed, Map):
        about_map(typed)
    elif isinstance(typed, Point):
        print(typed)
    elif isinstance(typed, Pose):
        print(typed)
    elif isinstance(typed, Region):
        about_region(typed)
    entity = Entity(entity_id, ltmc)
    if not entity.is_valid():
        print("Entity {} does not exist".format(entity_id))
        exit(1)
    attributes = entity.get_attributes()
    headers = ["Attribute Name", "Value"]
    rows = []
    for attr in attributes:
        unwrapped = attr.value
        name = None
        if isinstance(attr.value, int):
            other_entity = Entity(attr.value, ltmc)
            if other_entity.is_valid() and len(other_entity.get_attributes("name")) > 0:
                name = "\"" + other_entity.get_attributes("name")[0].value + "\""
                unwrapped = "{} ({})".format(str(unwrapped), name)
            else:
                unwrapped = str(attr.value)
        elif isinstance(attr.value, str):
            unwrapped = "\"{}\"".format(attr.value)

        rows.append([attr.attribute_name, unwrapped])
    print(tabulate(rows, headers))


def about_concept(concept_name):
    concept = ltmc.get_concept(concept_name)
    instances = concept.get_instances()
    print("{} instances of {}".format(len(instances), concept_name))
    print("ID \tName")
    for inst in instances:
        name_to_print = "-"
        if inst.get_name():
            name_to_print = inst.get_name()
        print("{}\t{}".format(inst.entity_id, name_to_print))


def about_map(map):
    print(map)


def about_region(region):
    print(region)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("entity_id_or_concept_name", type=str, nargs="?")
    args = parser.parse_args()
    if args.entity_id_or_concept_name is None:
        summarize_ltmc()
        return
    if args.entity_id_or_concept_name.isdigit():
        args.entity_id = int(args.entity_id_or_concept_name)
        args.concept_name = None
    else:
        args.concept_name = args.entity_id_or_concept_name
        args.entity_id = None

    if args.entity_id:
        about_id(args.entity_id)
    elif args.concept_name:
        about_concept(args.concept_name)


if __name__ == "__main__":
    main()
